name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseAs:
        description: 'Release as version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please.yml@main
    with:
      releaseAs: ${{ inputs.releaseAs }}
      packageName: "@voxpelli/eslint-config"
      bootstrapSha: 153462c87dea16a9effe0294274f450a5a45b7b2
