name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please-4.yml@main
    secrets: inherit
    with:
      lockfile: true
      publish-to-github: true
