name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please-bot.yml@main
    secrets: inherit
    with:
      app-id: '1082006'
      lockfile: true
      publish-to-github: true
