name: Rule Diff

on:
  pull_request:
    branches:
      - foo
      # - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

permissions:
  contents: read

jobs:
  diff:
    name: Generate diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PR source
        uses: actions/checkout@v4
        with:
          path: source
      - name: Checkout target ref ${{ github.base_ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: target
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Determine npm cache directory windows
        id: npm-cache-dir-windows
        if: runner.os == 'Windows'
        run: echo "dir=$(npm config get cache)" >> $env:GITHUB_OUTPUT
      - name: Determine npm cache directory non-windows
        id: npm-cache-dir
        if: runner.os != 'Windows'
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir-windows.outputs.dir || steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install the PR source
        run: 'npm ci --ignore-scripts --force'
        working-directory: ./source
      - name: Install the PR target
        run: 'npm ci --ignore-scripts --force'
        working-directory: ./target

      - name: Generate diff
        run: npx --no compare-eslint-configs ../target/.eslintrc .eslintrc -d -m --verbose-configs >> $GITHUB_STEP_SUMMARY
        working-directory: ./source
